export type Article={slug:string;title:string;excerpt:string;category:string;date:string;read:string;featured?:boolean;image?:string;body:string[]};
export const articles:Article[]=[
 {slug:'the-art-of-the-reset',title:'The art of the reset',excerpt:'Why the quietest moment in tennis may be the most important one.',category:'Mindset',date:'May 28, 2025',read:'6 min read',featured:true,image:'/images/court-report-hero.png',body:['Between points, a player has a rare opportunity: a small piece of time that belongs entirely to them. The best players make it look ordinary — a turn from the baseline, a breath, a return to the task at hand.','The reset is not a performance. It is a practice of attention. The crowd, the scoreboard and the last ball all recede as the next point comes into focus.','For recreational players, that same ritual can transform a match. Choose one simple cue: touch the strings, look at a fixed point, then let the next point be new.']},
 {slug:'court-craft-on-grass',title:'Court craft on grass',excerpt:'Low bounces, quick decisions and the graceful urgency of the game’s original surface.',category:'Technique',date:'May 22, 2025',read:'5 min read',body:['Grass asks players to arrive early and think clearly. The court rewards a compact swing and an alert first step.','The best preparation is simple: stay low, use the slice with purpose, and treat every short ball as an invitation rather than a surprise.']},
 {slug:'a-weekend-in-rome',title:'A weekend in Rome, through a tennis lens',excerpt:'Clay dust, long lunches and a city that understands drama.',category:'Travel',date:'May 16, 2025',read:'4 min read',body:['Rome offers tennis in vivid colour. The rally is part of a larger rhythm: espresso, afternoon heat, and the evening walk home.','It is a reminder that the sport is at its best when it belongs to a place.']},
 {slug:'the-return-of-the-return',title:'The return of the return',excerpt:'The most undervalued shot is having a very good spring.',category:'Analysis',date:'May 08, 2025',read:'7 min read',body:['A reliable return begins before the server moves. It is built on position, intent and the confidence to block the ball back with shape.','The aim is not always to win the point immediately. It is to make the rally possible.']}
];
export const events=[{date:'JUN 14',name:'Centre Court Sessions',place:'The Park Tennis Club · London',detail:'Open practice, coffee, and an on-court conversation about doubles.'},{date:'JUN 28',name:'Summer Social Invitational',place:'Willow Lawn Club · New York',detail:'A friendly all-levels mixer with music, light bites, and short-format matches.'},{date:'JUL 12',name:'Wimbledon Watch Morning',place:'Court Report Clubhouse · Online',detail:'A guided watch party and live editorial chat.'}];
export const categories=['All','Analysis','Mindset','Technique','Travel'];
